// packages/Demo/react/src/pages/child.jsx
import useGlobalStore from "../Store/useGlobalStore";

const Child = () => {
  const [reset, destroy] = useGlobalStore((state) => [
    state?.reset,
    state.destroy,
  ]);

  return (
    <div>
      <h3>Child</h3>
      <button onClick={() => reset()}>清空</button>
      <button onClick={() => destroy()}>销毁</button>
    </div>
  );
};

export default Child;

// packages/Demo/vue3/src/pages/child.vue
<!-- Component.vue -->
<script setup>
import useGlobalStore from "../Store/useGlobalStore";

const {reset,destroy}= useGlobalStore(state=>({
    reset:state.reset,
    destroy:state.destroy
}));
</script>

<template>
       <h3>Child </h3>
        <button @click="() => reset()">清空</button>
        <button @click="() => destroy()">销毁</button>
</template>
