// packages/Demo/react/src/pages/index.jsx
import useGlobalStore from "../Store/useGlobalStore";
import Child from "./child";

export const Test = () => {
  const globalStore = useGlobalStore((state) => state);
  const { bears, count, increase, reSet, radomCount } = globalStore;
  return (
    <div>
      <h3>Parent</h3>
      <div>
        bears ( {bears} ):
        <button onClick={() => increase()}>增加 </button>
        <button onClick={() => reSet()}>重置为10086</button>
      </div>

      <div>
        count ( {count} ): <button onClick={() => radomCount()}>随机</button>
      </div>

    </div>
  );
};

export default Test;

// packages/Demo/vue3/src/pages/index.vue
<!-- Component.vue -->
<script setup>
import useGlobalStore from "../Store/useGlobalStore";

const globalStore = useGlobalStore();
const { bears, count, increase, reSet, radomCount } = globalStore;
</script>

<template>
  <h3>Parent</h3>
  <div>
    bears ( {{ bears }} ):
    <button @click="() => increase(1)">增加</button>
    <button @click="() => reSet(10086)">重置为10086</button>
  </div>

  <div>
    count ( {{ count }} ): <button @click="() => radomCount()">随机</button>
  </div>
</template>
